#laminas:
#  build: .
#  dockerfile: Dockerfile
#  ports:
#   - "8080:80"
#  volumes:
#   - .:/var/www

version: '3'

services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "tiagopgr22@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "16543:80"
    depends_on:
      - postgres-db
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
